### ISSUE TITLE
[BUG]: AP Docker container throws an error while importing a piece from npm

### ISSUE THREAD

**Issue by antonconstantinov** [activepieces/activepieces#3151] opened 2023-11-09 14:21 UTC
**Description**
While importing my custom piece published to the npm Registry though the AP UI the Docker container outputs the error "SQLITE_CONSTRAINT: NOT NULL constraint failed: piece_metadata.displayName". The piece had been published as defined in the  [ActivePieces Docs](https://www.activepieces.com/docs/developers/sharing-pieces/community)

**To Reproduce**
1. Start the AP Docker container without configuring the webhook as described [here](https://www.activepieces.com/docs/install/options/docker)
2. Sign Up as John Doe with the email JD1@jd.jd and the same password (JD1@jd.jd)
3. Go to My Pieces option in the account dropdown
4. Click on the "Add Piece" button
5. Try to import [that](https://www.npmjs.com/package/@fluffy_hedgehog/piece-youtrack?activeTab=code) piece
6. See the error message in the Docker Container logs

**Expected behavior**
Piece should be added to the "My Pieces" list

**Screenshot with the error log**
![image](https://github.com/activepieces/activepieces/assets/122314755/e975e750-9095-4742-972c-71cb129bc72f)

**Comment by abuaboud** [comment] 2023-11-09 15:07
Hi @antonconstantinov I used the piece provided in the log screenshot and I could reproduce it.

Thank you, I am taking look soon!

**Comment by abuaboud** [comment] 2023-11-10 00:27
I couldn't check it today, I will check it out tmw!

**Comment by abuaboud** [comment] 2023-11-11 00:21
Hey @antonconstantinov, I discovered a problem.

I checked the log and noticed that action (test2.js) is importing the framework using a relative path instead of @activepieces/framework which doesn't exist in published version since the framework is standalone package but not relative path.


I'm not sure how it's being imported before it was published. If you would like any help could you schedule a call here? (: https://cal.com/abuaboud) I'd like to understand more to prevent this for other users

Closing this issue, feel free to reopen!

**Closed by abuaboud** 2023-11-11 00:21 UTC
Labels: 🐛 bug, question, backend
