### ISSUE TITLE
[BUG]: flows sometimes does not terminate

### ISSUE THREAD

**Issue by LK511** [activepieces/activepieces#4708] opened 2024-05-16 13:17 UTC
**Bug decription**
There is sometimes happening, flow freeze. It runs properly when I test it step by step. Flow sometimes freezes, when I start it from webhook or by test flow button on the same data. (It happened on many flows, not only one.)

**To Reproduce freeze what I did in my instance**
1. Go to New flow
2. Build flow with a database piece, a storage piece, a code piece to filter data in JSON received from the database and send a request to some web, merge a received response with the existing data, and add a condition based on the received http status by branch. If the response status is >=300, send the data via HTTP to another flow, else store the output to the database.
3. Start this flow from the webhook trigger
4. See the error, the running flow in runs does not terminate. When you will run the flow step by step, it works.

**Expected behavior**
Flow will always finish in a fail or in finished status, not stay in the running forever. I have flows, which shows running status many days

**Screenshots**
Running flow which does not terminate:
![image](https://github.com/activepieces/activepieces/assets/77941847/ddf32af9-a163-4bc6-a515-7bbc94c500d0)

2 days running flow which does nothing:
![image](https://github.com/activepieces/activepieces/assets/77941847/1365758e-5342-4dac-a552-77e41f5d2ff3)

**Additional context**
This usually happens, when it is started via webhook. When I open running flow, there is no information on which piece it is blocked, all pieces have a running circle icon.
![image](https://github.com/activepieces/activepieces/assets/77941847/04308c87-e66b-41c8-91fe-6f8a1d233baa)

There is no button to stop too long running flows started via webhook? There is set 600 to max timeout in the .env docker, but it seems, it does nothing when I change the value.

**Comment by abuaboud** [comment] 2024-05-17 09:25
Hi @LK511,

Thank you for reporting the issue. Are you using Docker Compose (with Redis/Postgres) or just a plain Docker image?

Do you see any errors in the backend logs? I think the flow threw an unexpected error that wasn't handled by the engine and stopped.

**Comment by LK511** [comment] 2024-05-17 13:27
In the docker container log, I see following:

`(node:8) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
2024/05/17 03:10PM 30 pid=8 hostname=apTest msg=[FlowWorker#executeFlow] flowRunId=CB8bZfBYkicjOTRYJP2v8 sandboxId=0 prepareTime=15889ms
2024/05/17 03:10PM 30 pid=8 hostname=apTest msg=sandbox, command: cd /usr/src/app/dist/packages/server/api/sandbox/0 && cross-env-shell AP_CODE_SANDBOX_TYPE=NO_OP AP_PIECES_SOURCE=CLOUD_AND_DB NODE_OPTIONS=--enable-source-maps  "/usr/local/bin/node" main.js EXECUTE_FLOW
2024/05/17 03:10PM 30 pid=8 hostname=apTest reqId=req_SYy9hgSShaitAQEkzuVad req={"method":"GET","url":"/v1/store-entries?key=STAGE","hostname":"127.0.0.1:3000","remoteAddress":"127.0.0.1","remotePort":41410} msg=incoming request
2024/05/17 03:10PM 30 pid=8 hostname=apTest reqId=req_SYy9hgSShaitAQEkzuVad res={"statusCode":200} responseTime=11.532426118850708 msg=request completed
2024/05/17 03:10PM 30 pid=8 hostname=apTest reqId=req_vOr6Sxj6u4EiFs0iraPFo req={"method":"GET","url":"/v1/worker/app-connections/Config_DB?projectId=w0UMzSmue5InrQO2LTBRI","hostname":"127.0.0.1:3000","remoteAddress":"127.0.0.1","remotePort":41420} msg=incoming request
2024/05/17 03:10PM 30 pid=8 hostname=apTest reqId=req_vOr6Sxj6u4EiFs0iraPFo res={"statusCode":200} responseTime=4.310935020446777 msg=request completed
2024/05/17 03:10PM 30 pid=8 hostname=apTest reqId=req_E4wFjPN92hvpMyIpAy2je req={"method":"POST","url":"/v1/webhooks/qQY14eURYVvKj3VWnUiFP","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":51978} msg=incoming request
2024/05/17 03:10PM 30 pid=8 hostname=apTest msg=[WebhookService#handshake] flowId=qQY14eURYVvKj3VWnUiFP
2024/05/17 03:10PM 30 pid=8 hostname=apTest msg=[WebhookService#callback] flowId=qQY14eURYVvKj3VWnUiFP
2024/05/17 03:10PM 30 pid=8 hostname=apTest reqId=req_E4wFjPN92hvpMyIpAy2je res={"statusCode":200} responseTime=33.83429002761841 msg=request completed
2024/05/17 03:10PM 30 pid=8 hostname=apTest msg=[FileService#save] fileId=9py57isqFfXZnPPsQiwSd data.length=892
2024/05/17 03:10PM 30 pid=8 hostname=apTest msg=[FlowWorker#executeFlow] flowRunId=CB8bZfBYkicjOTRYJP2v8 executionOutputStatus=SUCCEEDED sandboxId=0 duration=17807 ms
2024/05/17 03:10PM 30 pid=8 hostname=apTest reqId=req_6mYcNaFiHkZF3ELpIFd70 req={"method":"GET","url":"/v1/flow-runs/CB8bZfBYkicjOTRYJP2v8","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":51986} msg=incoming request
2024/05/17 03:10PM 30 pid=8 hostname=apTest reqId=req_6mYcNaFiHkZF3ELpIFd70 res={"statusCode":200} responseTime=18.367722988128662 msg=request completed
2024/05/17 03:10PM 30 pid=8 hostname=apTest reqId=req_nBO31fBOqSdQOGdbHpxNX req={"method":"GET","url":"/v1/pieces/@activepieces/piece-schedule","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":52000} msg=incoming request
2024/05/17 03:10PM 30 pid=8 hostname=apTest reqId=req_nBO31fBOqSdQOGdbHpxNX res={"statusCode":200} responseTime=6.827796936035156 msg=request completed
2024/05/17 03:10PM 30 pid=8 hostname=apTest reqId=req_tnBDegn1LtofmSRdZ7Jcn req={"method":"GET","url":"/v1/trigger-events?flowId=MQBnhOVJoPapqPUsdmg4Z","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":52012} msg=incoming request
2024/05/17 03:10PM 30 pid=8 hostname=apTest reqId=req_tnBDegn1LtofmSRdZ7Jcn res={"statusCode":200} responseTime=6.050209045410156 msg=request completed
2024/05/17 03:10PM 30 pid=8 hostname=apTest reqId=req_AX2pPbWCiITwozoUiVWUc req={"method":"GET","url":"/v1/users/projects/w0UMzSmue5InrQO2LTBRI","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":52024} msg=incoming request
2024/05/17 03:10PM 30 pid=8 hostname=apTest reqId=req_AX2pPbWCiITwozoUiVWUc res={"statusCode":200} responseTime=1.8395719528198242 msg=request completed
2024/05/17 03:10PM 30 pid=8 hostname=apTest reqId=req_CjSn6WlB4FiE81BSh69sc req={"method":"GET","url":"/v1/app-connections?limit=99999&projectId=w0UMzSmue5InrQO2LTBRI","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":52026} msg=incoming request
2024/05/17 03:10PM 30 pid=8 hostname=apTest reqId=req_CjSn6WlB4FiE81BSh69sc res={"statusCode":200} responseTime=12.643709897994995 msg=request completed
2024/05/17 03:10PM 30 pid=8 hostname=apTest msg=sandbox, command: cd /usr/src/app/dist/packages/server/api/sandbox/0 && cross-env-shell AP_CODE_SANDBOX_TYPE=NO_OP AP_PIECES_SOURCE=CLOUD_AND_DB NODE_OPTIONS=--enable-source-maps  "/usr/local/bin/node" main.js EXECUTE_TRIGGER_HOOK
2024/05/17 03:10PM 30 pid=8 hostname=apTest msg=[FlowRunSideEffects#start] flowRunId=F4Wb5xfrdMyEPArk50t6e executionType=BEGIN
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_5VoIQRGU9mh0xor3GG8xC req={"method":"GET","url":"/v1/users/projects/w0UMzSmue5InrQO2LTBRI","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":47558} msg=incoming request
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_5VoIQRGU9mh0xor3GG8xC res={"statusCode":200} responseTime=10.715939044952393 msg=request completed
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_IpL5S7jgJpclpkZUnGqGH req={"method":"GET","url":"/v1/flows?limit=10&cursor=&projectId=w0UMzSmue5InrQO2LTBRI","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":47562} msg=incoming request
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_SrnAnVzuoKYN20OpJrgPG req={"method":"GET","url":"/v1/flows/count","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":47576} msg=incoming request
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_SrnAnVzuoKYN20OpJrgPG res={"statusCode":200} responseTime=3.716343879699707 msg=request completed
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_WDWrOepjT0R9o71gMwq6z req={"method":"GET","url":"/v1/flows/count?folderId=NULL","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":47582} msg=incoming request
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_Yp2w1E62OXiHA7ob4nDFc req={"method":"GET","url":"/v1/folders?limit=1000000","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":47586} msg=incoming request
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_Yp2w1E62OXiHA7ob4nDFc res={"statusCode":200} responseTime=12.882106065750122 msg=request completed
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_WDWrOepjT0R9o71gMwq6z res={"statusCode":200} responseTime=19.819901943206787 msg=request completed
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_IpL5S7jgJpclpkZUnGqGH res={"statusCode":200} responseTime=236.18245100975037 msg=request completed
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_ur74hToVQJq3cm0giX1TR req={"method":"GET","url":"/v1/users/projects?limit=99999","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":47598} msg=incoming request
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_ur74hToVQJq3cm0giX1TR res={"statusCode":200} responseTime=2.829158067703247 msg=request completed
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_DC53aCor9rJ2fUtloVy4C req={"method":"GET","url":"/v1/users/projects/w0UMzSmue5InrQO2LTBRI","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":47606} msg=incoming request
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_DC53aCor9rJ2fUtloVy4C res={"statusCode":200} responseTime=3.1583521366119385 msg=request completed
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_JkDb6DdQVJfQ0cAaIylLN req={"method":"GET","url":"/v1/users/projects/w0UMzSmue5InrQO2LTBRI","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":47612} msg=incoming request
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_JkDb6DdQVJfQ0cAaIylLN res={"statusCode":200} responseTime=2.33986496925354 msg=request completed
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_hRwr9JECLzaERQIt9cg91 req={"method":"GET","url":"/v1/folders?limit=1000000","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":47614} msg=incoming request
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_yLd2pzyVHkyzMt7m4K2Gr req={"method":"GET","url":"/v1/flows?limit=10&cursor=&projectId=w0UMzSmue5InrQO2LTBRI&folderId=6XXe5qBVHn8kxkxjJVvV4","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":47622} msg=incoming request
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_hRwr9JECLzaERQIt9cg91 res={"statusCode":200} responseTime=14.211485862731934 msg=request completed
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_yLd2pzyVHkyzMt7m4K2Gr res={"statusCode":200} responseTime=90.1306459903717 msg=request completed
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_NPVBMSJWWXRbf0Lb6z5ae req={"method":"GET","url":"/v1/platforms/Ftt4SjAaPA2iA48fm4puE","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":47628} msg=incoming request
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_NPVBMSJWWXRbf0Lb6z5ae res={"statusCode":200} responseTime=2.909256935119629 msg=request completed
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_s7YUb3qWm4d2svADmOwds req={"method":"GET","url":"/v1/platforms/Ftt4SjAaPA2iA48fm4puE","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":47636} msg=incoming request
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_s7YUb3qWm4d2svADmOwds res={"statusCode":200} responseTime=1.9442708492279053 msg=request completed
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_7SjEmpHFOmkK35KNzZWKk req={"method":"GET","url":"/v1/pieces/@activepieces/piece-approval?version=0.1.7","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":47652} msg=incoming request
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_p71ZVNYVDPnWA5481ZQfp req={"method":"GET","url":"/v1/pieces/@activepieces/piece-date-helper?version=0.0.7","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":47668} msg=incoming request
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_N5y2FQeVHRdtWuyqK10E8 req={"method":"GET","url":"/v1/pieces/@activepieces/piece-webhook?version=~0.0.2","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":47672} msg=incoming request
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_0jaoMfd2oeo7yEn1K7Ute req={"method":"GET","url":"/v1/platforms/Ftt4SjAaPA2iA48fm4puE","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":47682} msg=incoming request
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_N5y2FQeVHRdtWuyqK10E8 res={"statusCode":200} responseTime=21.751673936843872 msg=request completed
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_7SjEmpHFOmkK35KNzZWKk res={"statusCode":200} responseTime=34.06328821182251 msg=request completed
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_p71ZVNYVDPnWA5481ZQfp res={"statusCode":200} responseTime=45.81261205673218 msg=request completed
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_0jaoMfd2oeo7yEn1K7Ute res={"statusCode":200} responseTime=42.485761880874634 msg=request completed
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_ogrsEjkIXqsiXRqycrvFo req={"method":"GET","url":"/v1/platforms/Ftt4SjAaPA2iA48fm4puE","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":47686} msg=incoming request
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_ogrsEjkIXqsiXRqycrvFo res={"statusCode":200} responseTime=3.1949520111083984 msg=request completed
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_3JejOihBUMXWdVuRkULxe req={"method":"GET","url":"/v1/platforms/Ftt4SjAaPA2iA48fm4puE","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":47692} msg=incoming request
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_3JejOihBUMXWdVuRkULxe res={"statusCode":200} responseTime=2.616960048675537 msg=request completed
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_BAbWfHwkvZzH9Dx7jmald req={"method":"GET","url":"/v1/platforms/Ftt4SjAaPA2iA48fm4puE","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":47704} msg=incoming request
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_BAbWfHwkvZzH9Dx7jmald res={"statusCode":200} responseTime=2.233267068862915 msg=request completed
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_l5xeqDegQdc9J6HzjLQxO req={"method":"GET","url":"/v1/platforms/Ftt4SjAaPA2iA48fm4puE","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":47714} msg=incoming request
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_l5xeqDegQdc9J6HzjLQxO res={"statusCode":200} responseTime=2.6313610076904297 msg=request completed
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_IpHGnhPP0bdsYpIPS8OGc req={"method":"GET","url":"/v1/platforms/Ftt4SjAaPA2iA48fm4puE","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":47716} msg=incoming request
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_IpHGnhPP0bdsYpIPS8OGc res={"statusCode":200} responseTime=2.2594659328460693 msg=request completed
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_qvuNOWpmoOmOMlrwgeILU req={"method":"GET","url":"/v1/platforms/Ftt4SjAaPA2iA48fm4puE","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":47726} msg=incoming request
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_qvuNOWpmoOmOMlrwgeILU res={"statusCode":200} responseTime=2.2634658813476562 msg=request completed
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_FtxDJagyXZojP9xsDiX3o req={"method":"GET","url":"/v1/platforms/Ftt4SjAaPA2iA48fm4puE","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":47742} msg=incoming request
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_FtxDJagyXZojP9xsDiX3o res={"statusCode":200} responseTime=2.0878689289093018 msg=request completed
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_5dmYSGuj4XjvhG9vOijym req={"method":"GET","url":"/v1/flows?limit=1000&cursor=&projectId=w0UMzSmue5InrQO2LTBRI","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":47750} msg=incoming request
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_gZYKUfpx28KWlWRck1fun req={"method":"GET","url":"/v1/users/projects/w0UMzSmue5InrQO2LTBRI","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":47752} msg=incoming request
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_gZYKUfpx28KWlWRck1fun res={"statusCode":200} responseTime=209.26745700836182 msg=request completed
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_gJLER9zPi1wQuqkqVC2Gy req={"method":"GET","url":"/v1/users/projects/w0UMzSmue5InrQO2LTBRI","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":47762} msg=incoming request
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_gJLER9zPi1wQuqkqVC2Gy res={"statusCode":200} responseTime=5.703313827514648 msg=request completed
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_5dmYSGuj4XjvhG9vOijym res={"statusCode":200} responseTime=662.0114579200745 msg=request completed
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_0CBc2vmNkBA2keFPcZImi req={"method":"GET","url":"/v1/flow-runs?projectId=w0UMzSmue5InrQO2LTBRI&limit=10","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":47776} msg=incoming request
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_0CBc2vmNkBA2keFPcZImi res={"statusCode":200} responseTime=9.7324538230896 msg=request completed
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_dgCCvKMdUuVUVkqgN7ucf req={"method":"GET","url":"/v1/flow-runs?projectId=w0UMzSmue5InrQO2LTBRI&limit=10","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":37726} msg=incoming request
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_dgCCvKMdUuVUVkqgN7ucf res={"statusCode":200} responseTime=11.240331172943115 msg=request completed
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_XPaAhGzHGQiUefXQKoLwQ req={"method":"GET","url":"/v1/flow-runs?projectId=w0UMzSmue5InrQO2LTBRI&limit=10","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":54874} msg=incoming request
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_XPaAhGzHGQiUefXQKoLwQ res={"statusCode":200} responseTime=12.942605972290039 msg=request completed
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_f96be19A92419VvdXmTWr req={"method":"GET","url":"/v1/flow-runs?projectId=w0UMzSmue5InrQO2LTBRI&limit=10","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":55636} msg=incoming request
2024/05/17 03:11PM 30 pid=8 hostname=apTest reqId=req_f96be19A92419VvdXmTWr res={"statusCode":200} responseTime=12.30991506576538 msg=request completed
2024/05/17 03:12PM 30 pid=8 hostname=apTest reqId=req_qAHhzmP2mythh6dfVDa8l req={"method":"GET","url":"/v1/flow-runs?projectId=w0UMzSmue5InrQO2LTBRI&limit=10","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":32880} msg=incoming request
2024/05/17 03:12PM 30 pid=8 hostname=apTest reqId=req_qAHhzmP2mythh6dfVDa8l res={"statusCode":200} responseTime=17.555136919021606 msg=request completed
2024/05/17 03:12PM 30 pid=8 hostname=apTest reqId=req_cdoZP72z3zBeG5jgRuTl4 req={"method":"GET","url":"/v1/flow-runs?projectId=w0UMzSmue5InrQO2LTBRI&limit=10","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":39468} msg=incoming request
2024/05/17 03:12PM 30 pid=8 hostname=apTest reqId=req_cdoZP72z3zBeG5jgRuTl4 res={"statusCode":200} responseTime=13.21270203590393 msg=request completed
2024/05/17 03:12PM 30 pid=8 hostname=apTest reqId=req_3eDxQ3SLrd3TByFFxzEO8 req={"method":"GET","url":"/v1/flow-runs?projectId=w0UMzSmue5InrQO2LTBRI&limit=10","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":49094} msg=incoming request
2024/05/17 03:12PM 30 pid=8 hostname=apTest reqId=req_3eDxQ3SLrd3TByFFxzEO8 res={"statusCode":200} responseTime=12.091318845748901 msg=request completed
2024/05/17 03:12PM 30 pid=8 hostname=apTest reqId=req_ctaqq6EW37fO69QX73mlw req={"method":"GET","url":"/v1/flow-runs?projectId=w0UMzSmue5InrQO2LTBRI&limit=10","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":58940} msg=incoming request
2024/05/17 03:12PM 30 pid=8 hostname=apTest reqId=req_ctaqq6EW37fO69QX73mlw res={"statusCode":200} responseTime=11.085433959960938 msg=request completed
2024/05/17 03:12PM 30 pid=8 hostname=apTest reqId=req_K5dtkVNEpVqZANVdEAk2z req={"method":"GET","url":"/v1/flow-runs?projectId=w0UMzSmue5InrQO2LTBRI&limit=10","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":33332} msg=incoming request
2024/05/17 03:12PM 30 pid=8 hostname=apTest reqId=req_K5dtkVNEpVqZANVdEAk2z res={"statusCode":200} responseTime=13.640697002410889 msg=request completed
2024/05/17 03:12PM 30 pid=8 hostname=apTest reqId=req_Xl6SoMTv7LvErvKNXpCIR req={"method":"GET","url":"/v1/flow-runs?projectId=w0UMzSmue5InrQO2LTBRI&limit=10","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":50048} msg=incoming request
2024/05/17 03:12PM 30 pid=8 hostname=apTest reqId=req_Xl6SoMTv7LvErvKNXpCIR res={"statusCode":200} responseTime=11.905322074890137 msg=request completed
2024/05/17 03:13PM 30 pid=8 hostname=apTest reqId=req_wtrWFd6hguAagkGhxQFTR req={"method":"GET","url":"/v1/flow-runs?projectId=w0UMzSmue5InrQO2LTBRI&limit=10","hostname":"apTest.local","remoteAddress":"127.0.0.1","remotePort":42400} msg=incoming request
2024/05/17 03:13PM 30 pid=8 hostname=apTest reqId=req_wtrWFd6hguAagkGhxQFTR res={"statusCode":200} responseTime=11.094235181808472 msg=request completed`

It looks like it still starts the same flow. if I understand the log properly, but there is started only one flow in the run tab: 
![image](https://github.com/activepieces/activepieces/assets/77941847/b380ab39-9baf-426a-a7d0-cddacdd2fbfa)

I see no Error in the log.


I am using Docker image connected to our Postgres and Redis DB. The used user has all permissions enabled, no limitations on the user are set. I am using the user for managing everything in the database.

**Comment by LK511** [comment] 2024-05-22 14:39
I have found a solution, how to solve this issue. There was AP_QUEUE_MODE set to REDIS, which caused the freeze. When I changed it to MEMORY, it is running correctly. But with memory, the response latency of the AP web UI is incerased many times.

**Comment by abuaboud** [comment] 2024-09-06 02:22
Hi @LK511,

That’s unusual—it should be Redis, which is generally more stable as it persist runs. Many issues related to stuck runs have been addressed over the past two months, so I’m not certain if this particular issue has been resolved, but I’m unable to reproduce it on my end.

If you encounter this problem again, please enable BullMQ and check the Bull Board for the stuck run along with any associated errors.

For further assistance, you can refer to our [troubleshooting guide](https://www.activepieces.com/docs/install/troubleshooting).

Let us know if you’re able to reproduce this issue on newer versions, I am closing the issue but please feel free to reopen.

Best regards,  
Mo.

**Closed by abuaboud** 2024-09-06 02:22 UTC
Labels: 🤷‍♂️🤷‍♀️ untriaged
