### ISSUE TITLE
Common openai api support.

### ISSUE THREAD

**Issue by agczsz** [activepieces/activepieces#4729] opened 2024-05-20 08:45 UTC
**Is your feature request related to a problem? Please describe.**
I can't use openai with my own api I'm always frustrated when write the code

**Describe the solution you'd like**
![image](https://github.com/activepieces/activepieces/assets/121206519/9b137df3-f3ac-43f5-a5a2-8a1c4e8670e2)

**Describe alternatives you've considered**
I Could choose my own api,and stop the key verify because the key may not as the normal.
and add the lenth limit.

**Comment by agczsz** [comment] 2024-05-20 08:46
I Could choose my own api url and model,but not write in code,for the server follow the openai official use.

**Comment by abuaboud** [comment] 2024-09-18 01:57
We will work on it 🙏

@anasbarg 

Closing as duplicate of https://github.com/activepieces/activepieces/issues/4750

**Closed** 2024-09-18 01:57 UTC
