### ISSUE TITLE
Import & Export workflows/projects

### ISSUE THREAD

**Issue by kanarelo** [activepieces/activepieces#841] opened 2023-03-19 15:13 UTC
**Is your feature request related to a problem? Please describe.**
There's a need for the ability to import/export workflows and projects.

**Describe the solution you'd like**
I would like the ability to import & export workflows without losing the structure of branches and other logic steps and their parameters/arguments.
The feature can be button on the list of flows and/or a button inside the flow designer.

**Describe alternatives you've considered**
I have considered writing a script that reads the database and exports JSON data

**Additional context**
This feature can help a lot in backup and collaboration.

**Comment by abuaboud** [comment] 2023-03-22 13:53
Closing this ticket as it's duplicate of https://github.com/activepieces/activepieces/issues/558

**Closed by abuaboud** 2023-03-22 13:53 UTC
Labels: duplicate, ⭐ enhancement, frontend
