### ISSUE TITLE
Question on isolate sandbox execution

### ISSUE THREAD

**Issue by sheldondz** [activepieces/activepieces#2951] opened 2023-10-13 09:44 UTC
The default package on docker hub activepieces/activepieces:latest does not see to work using isolate, we get this error 

```
POST /api/v1/pieces/options

{
    "statusCode": 500,
    "code": "ENOENT",
    "error": "Internal Server Error",
    "message": "ENOENT: no such file or directory, open '/var/local/lib/isolate/1/box/_standardOutput.txt'"
}
```

**Comment by abuaboud** [comment] 2023-10-13 09:46
Hi @sheldondz what are the steps to reproduce?

**Comment by sheldondz** [comment] 2023-10-13 09:55
was trying to test the setup locally by SETTING the following environment variables
```
AP_SIGN_UP_ENABLED=true
AP_EXECUTION_MODE=SANDBOXED
```
which throws the error while creating flows, the options api call.

**Comment by abuaboud** [comment] 2023-10-13 09:56
Can you change AP_ENVIRONMENT to prod, does it work?

**Comment by sheldondz** [comment] 2023-10-13 10:16
Getting the same error with AP_ENVIRONMENT=prod

**Comment by sheldondz** [comment] 2023-10-13 10:18
in the ap_base.dockerfile i see this line

```
COPY packages/backend/src/assets/default.cf /usr/local/etc/isolate
```

but don't see the isolate binary installed anywhere in the dockerfile

**Comment by abuaboud** [comment] 2023-10-13 10:19
Can you try it on the cloud or another app?

We are using the same settings on the cloud and it is working for me

**Comment by abuaboud** [comment] 2023-10-24 22:34
Hi @sheldondz I am closing this issue, please reopen if you still have the issue.

**Closed as not planned by abuaboud** 2023-10-24 22:34 UTC
Labels: 🤷‍♂️🤷‍♀️ untriaged

**Comment by luizeof** [comment] 2023-12-28 22:45
@abuaboud same issue here

![image](https://github.com/activepieces/activepieces/assets/257004/6e2a145f-19a0-4cd9-aa1a-56fa1259d042)

**Comment by abuaboud** [comment] 2023-12-28 22:52
@luizeof can you please check if the docker container is privileged?

**Comment by luizeof** [comment] 2023-12-28 23:00
> @luizeof can you please check if the docker container is privileged?

I tested it now and it gave the same error, I'm using docker swarm.

![Captura de Tela 2023-12-28 às 19 59 39](https://github.com/activepieces/activepieces/assets/257004/692d30b4-1ca0-4b3f-b827-1a108253c3ca)

**Comment by izdrail** [comment] 2024-10-30 09:59
> > @luizeof can you please check if the docker container is privileged?
> 
> I tested it now and it gave the same error, I'm using docker swarm.
> 
> ![123](https://private-user-images.githubusercontent.com/257004/293285612-cc26e426-4b0d-4823-8686-a10cde0d1fd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyODI2NDAsIm5iZiI6MTczMDI4MjM0MCwicGF0aCI6Ii8yNTcwMDQvMjkzMjg1NjEyLWNjMjZlNDI2LTRiMGQtNDgyMy04Njg2LWExMGNkZTBkMWZkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQwOTU5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMjE1N2U1ZjBlZDg5YTc4ZmU0YzQ0YTljZDk1NTcxM2JkM2ZlN2I4NzYxZDc4ODhmNTUyZDFlMzdkYTIyYTFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1Jre5sV7o9Cf9WaQuX-ZDOzSXnKON__ERfqeHfk5y_A)

If your comming from coolify you'll have to edit the compose file :)

**Comment by luizeof** [comment] 2024-10-30 17:55
> > > @luizeof can you please check if the docker container is privileged?
> > 
> > 
> > I tested it now and it gave the same error, I'm using docker swarm.
> > ![123](https://private-user-images.githubusercontent.com/257004/293285612-cc26e426-4b0d-4823-8686-a10cde0d1fd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyODI2NDAsIm5iZiI6MTczMDI4MjM0MCwicGF0aCI6Ii8yNTcwMDQvMjkzMjg1NjEyLWNjMjZlNDI2LTRiMGQtNDgyMy04Njg2LWExMGNkZTBkMWZkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQwOTU5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMjE1N2U1ZjBlZDg5YTc4ZmU0YzQ0YTljZDk1NTcxM2JkM2ZlN2I4NzYxZDc4ODhmNTUyZDFlMzdkYTIyYTFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1Jre5sV7o9Cf9WaQuX-ZDOzSXnKON__ERfqeHfk5y_A)
> 
> If your comming from coolify you'll have to edit the compose file :)

Since the issue was ignored, I ended up giving up on using the project.
