### ISSUE TITLE
[BUG]: emojis in Gmail not showing

### ISSUE THREAD

**Issue by ashrafsamhouri** [activepieces/activepieces#1165] opened 2023-04-27 17:49 UTC
I sent this email using Activepieces:
<img width="550" alt="Screenshot 2023-04-27 at 20 48 21" src="https://user-images.githubusercontent.com/97393596/234949746-e5812ed4-041b-4ef2-ab6f-8369a335a0ff.png">

Showed like this in my inbox:
<img width="450" alt="Screenshot 2023-04-27 at 20 48 26" src="https://user-images.githubusercontent.com/97393596/234949781-9372585f-3cc9-4dd6-ae82-68d02a4fabdc.png">

**Comment by Suriteka** [comment] 2023-04-29 14:17
@abuaboud as a first time contributor, I'll take this issue. ✌️

**Comment by abuaboud** [comment] 2023-04-29 14:18
Thaank you @Suriteka , assigned it to you :D

**Comment by Suriteka** [comment] 2023-05-01 15:26
@abuaboud Thanks a lot, after a first look I can reproduce the bug.

<img width="540" alt="Capture d’écran 2023-05-01 à 17 16 20" src="https://user-images.githubusercontent.com/31373819/235475492-87a367c9-ea6b-4a8c-9c75-6775bdf1a8a9.png">

After looking to [Gmail Api](https://developers.google.com/gmail/api/reference/rest/v1/users.messages#Message) our string is also in Base64 so it should be good. I think that in `send-email-action` this line have a problem.
 ```
 SendEmailRequestBody = {
    raw: Buffer.from(message).toString("base64").replace(/\+/g, '-').replace(/\//g, '_'),
};
``` 
After some investigation I've found that the problem is common. As you can see [here](https://stackoverflow.com/a/65166423/5840917).

Do you have an idea to fix it? I've tested some things like doing but it's also not working.

```
Buffer.from(message, "base64").replace(/\+/g, '-').replace(/\//g, '_')
```
 
Maybe you have an idea?

**Comment by abuaboud** [comment] 2023-05-02 08:59
Did you try the suggest solution String.fromCodePoint? @Suriteka

**Comment by Suriteka** [comment] 2023-05-12 10:24
> Did you try the suggest solution String.fromCodePoint? @Suriteka

I'll try it and keep you in touch, thanks @abuaboud !

**Comment by abuaboud** [comment] 2023-05-18 18:40
Thank you @Suriteka ,This approach lead me to this solution where I can specify base64 in the header, Opened PR :D

```ts
		const subjectBase64 = Buffer.from(configValue.propsValue['subject']).toString("base64");
		const headers = [
			`subject: =?UTF-8?B?${subjectBase64}?=`,
            "to: " + configValue.propsValue['receiver'].join(', '), // Join all email addresses with a comma
			"mime-version: 1.0",
			"content-type: text/html"
		];
```

**Closed** 2023-05-18 18:43 UTC
Labels: good first issue, 🔌 pieces, 💥 action
