### ISSUE TITLE
[BUG]: npm run serve:backend error

### ISSUE THREAD

**Issue by tdergouzi** [activepieces/activepieces#3600] opened 2024-01-11 02:38 UTC
Descirption
Got an error when i run npm run serve:backend in local environment.

Error message
![Screenshot 2024-01-11 at 10 36 54](https://github.com/activepieces/activepieces/assets/42488870/f7e9bd5c-0d9c-4c37-8a0a-4058c29a9609)

My env
operation system: MacOS
node version: v18.17.1
npm version: 9.6.7
code version: latest

Additional context
I got no error when installing the dependencies. I think this may be a bug in code, waiting for reply, thanks.
Sorry for wrong description in issue-3590.

**Comment by abuaboud** [comment] 2024-01-21 19:53
Hi @tdergouzi 

I missed this issue, the CI/CD are passing fine line and I can't reproduce it locally neither any of my co-workers.

As workaround run it in dev container, please let us know if there is a way to reproduce.

**Comment by abuaboud** [comment] 2024-02-14 01:01
Hi @tdergouzi,

I still haven't had any luck reproducing the issue. I am closing the issue for now. Please try again on the latest version and let me know if you still encounter any issues.

**Closed by abuaboud** 2024-02-14 01:01 UTC
Labels: question
