### ISSUE TITLE
[BUG]: node-fetch npm version in "Code"

### ISSUE THREAD

**Issue by DivineFarm** [activepieces/activepieces#5291] opened 2024-08-07 08:34 UTC
**Describe the bug**
When installing node-fetch through "add npm package" in the "CODE" node section, the node-fetch version by default is not correct.

**To Reproduce**
1. Go to 'Code' node
2. Click on 'add npm package'
3. Enter 'node-fetch'
4. See version in "dependencies" as version 3.3.2
{
  "dependencies": {
    "node-fetch": "3.3.2"
  }
}

**Expected behavior** (As per the last available version)
{
  "dependencies": {
    "node-fetch": "2.7.0"
  }
}

**Screenshots**
![image](https://github.com/user-attachments/assets/4f043552-b71c-4182-93a6-cf9f454d84c7)

**Additional context**
The version mismatch doesn't allow the code to run

**Comment by kishanprmr** [comment] 2024-08-12 09:10
Hello @DivineFarm, according to the [releases page](https://github.com/node-fetch/node-fetch/releases) for node-fetch, version 3.3.2 is the latest. The code piece installs the latest version of npm packages. Could you provide details about the error you're encountering with the latest version?

**Comment by DivineFarm** [comment] 2024-08-14 07:20
The issue I am running into is when using the latest version of node-fetch while version 2.7.0 is running fine.

## ERROR

`"Compilation Error: \"index.ts(16,22): error TS2339: Property 'items' does not exist on type 'unknown'.\nindex.ts(16,44): error TS2339: Property 'items' does not exist on type 'unknown'.\nindex.ts(18,26): error TS2339: Property 'items' does not exist on type 'unknown'.\nindex.ts(19,29): error TS2339: Property 'items' does not exist on type 'unknown'.\nindex.ts(20,35): error TS2339: Property 'items' does not exist on type 'unknown'.\nindex.ts(21,34): error TS2339: Property 'items' does not exist on type 'unknown'.\nindex.ts(22,34): error TS2339: Property 'items' does not exist on type 'unknown'.\nindex.ts(40,23): error TS2339: Property 'items' does not exist on type 'unknown'.\nindex.ts(40,42): error TS2339: Property 'items' does not exist on type 'unknown'.\nindex.ts(41,43): error TS2339: Property 'items' does not exist on type 'unknown'.\nindex.ts(56,37): error TS2339: Property 'nextPageToken' does not exist on type 'unknown'.\n\""
`

## ORIGINAL CODE:

```
import fetch from 'node-fetch';

export const code = async (inputs) => { 
  const apiKey = 'YOUTUBE_API_KEY'; // Your provided API key 
  const playlistId = inputs.playlistId; // Accepting playlistId from inputs 
  const playlistUrl = `https://youtube.googleapis.com/youtube/v3/playlists?part=snippet,contentDetails&id=${playlistId}&key=${apiKey}`;

  try { 
    const playlistResponse = await fetch(playlistUrl); 
    const playlistData = await playlistResponse.json();

    // Log the entire response for debugging
    console.log('Playlist Data Response:', playlistData);

    // Check if items exist
    if (playlistData.items && playlistData.items.length > 0) {
      const playlistInfo = {
        id: playlistData.items[0].id,
        title: playlistData.items[0].snippet.title,
        description: playlistData.items[0].snippet.description,
        thumbnails: playlistData.items[0].snippet.thumbnails,
        videoCount: playlistData.items[0].contentDetails.itemCount
      };

      console.log('Playlist Info:', playlistInfo);

      // Fetch the videos in the playlist
      const videos = []; // Array to hold all videos
      let nextPageToken = ''; // Variable to hold the next page token

      do {
        const videoUrl = `https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=${playlistId}&key=${apiKey}&pageToken=${nextPageToken}`;
        const videoResponse = await fetch(videoUrl);
        const videoData = await videoResponse.json();

        // Log the video data response for debugging
        console.log('Video Data Response:', videoData);

        // Check if video items exist
        if (videoData.items && videoData.items.length > 0) {
          const fetchedVideos = videoData.items.map(video => ({
            videoId: video.snippet.resourceId.videoId,
            title: video.snippet.title,
            description: video.snippet.description,
            publishDate: video.snippet.publishedAt,
            channelId: video.snippet.channelId,
            thumbnails: {
              default: video.snippet.thumbnails.default.url,
              medium: video.snippet.thumbnails.medium.url,
              high: video.snippet.thumbnails.high.url,
              standard: video.snippet.thumbnails.standard.url
            }
          }));

          videos.push(...fetchedVideos); // Add fetched videos to the main array
          nextPageToken = videoData.nextPageToken; // Update the nextPageToken for the next iteration
        } else {
          console.error('No videos found in the playlist.');
          return { error: 'The playlist doesn\'t contain any videos' }; // Return error message in JSON format
        }
      } while (nextPageToken); // Continue until there are no more pages

      console.log('All Videos in Playlist:', videos);

      // Return both playlist info and all videos as a JSON object
      return {
        playlistInfo,
        videos
      };
    } else {
      console.error('No playlist found for the given ID.');
      return { error: 'This playlist ID doesn\'t contain any information' }; // Return error message in JSON format
    }
  } catch (error) { 
    console.error('Error fetching playlist details:', error); 
    return { error: `Error fetching playlist details: ${error.message}` }; // Return error message in JSON format 
  } 
};
```

**Comment by abuaboud** [comment] 2024-10-13 20:27
@DivineFarm 

the issue is this code doesn't compile in typescript, I tried to fix it manually (not tested), by adding the type : any instead of unknown from response json() function 
```ts
import fetch from 'node-fetch';

export const code = async (inputs) => { 
  const apiKey = 'YOUTUBE_API_KEY'; // Your provided API key 
  const playlistId = inputs.playlistId; // Accepting playlistId from inputs 
  const playlistUrl = `https://youtube.googleapis.com/youtube/v3/playlists?part=snippet,contentDetails&id=${playlistId}&key=${apiKey}`;

  try { 
    const playlistResponse = await fetch(playlistUrl); 
    const playlistData:any = await playlistResponse.json();

    // Log the entire response for debugging
    console.log('Playlist Data Response:', playlistData);

    // Check if items exist
    if (playlistData.items && playlistData.items.length > 0) {
      const playlistInfo = {
        id: playlistData.items[0].id,
        title: playlistData.items[0].snippet.title,
        description: playlistData.items[0].snippet.description,
        thumbnails: playlistData.items[0].snippet.thumbnails,
        videoCount: playlistData.items[0].contentDetails.itemCount
      };

      console.log('Playlist Info:', playlistInfo);

      // Fetch the videos in the playlist
      const videos = []; // Array to hold all videos
      let nextPageToken = ''; // Variable to hold the next page token

      do {
        const videoUrl = `https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=${playlistId}&key=${apiKey}&pageToken=${nextPageToken}`;
        const videoResponse = await fetch(videoUrl);
        const videoData:any = await videoResponse.json();

        // Log the video data response for debugging
        console.log('Video Data Response:', videoData);

        // Check if video items exist
        if (videoData.items && videoData.items.length > 0) {
          const fetchedVideos = videoData.items.map(video => ({
            videoId: video.snippet.resourceId.videoId,
            title: video.snippet.title,
            description: video.snippet.description,
            publishDate: video.snippet.publishedAt,
            channelId: video.snippet.channelId,
            thumbnails: {
              default: video.snippet.thumbnails.default.url,
              medium: video.snippet.thumbnails.medium.url,
              high: video.snippet.thumbnails.high.url,
              standard: video.snippet.thumbnails.standard.url
            }
          }));

          videos.push(...fetchedVideos); // Add fetched videos to the main array
          nextPageToken = videoData.nextPageToken; // Update the nextPageToken for the next iteration
        } else {
          console.error('No videos found in the playlist.');
          return { error: 'The playlist doesn\'t contain any videos' }; // Return error message in JSON format
        }
      } while (nextPageToken); // Continue until there are no more pages

      console.log('All Videos in Playlist:', videos);

      // Return both playlist info and all videos as a JSON object
      return {
        playlistInfo,
        videos
      };
    } else {
      console.error('No playlist found for the given ID.');
      return { error: 'This playlist ID doesn\'t contain any information' }; // Return error message in JSON format
    }
  } catch (error) { 
    console.error('Error fetching playlist details:', error); 
    return { error: `Error fetching playlist details: ${(error as any).message}` }; // Return error message in JSON format 
  } 
};
```

Please let us know if that works.

I am closing this token, feel free reopen If you still have the issue on latest version 0.34.2 of Activepieces.

**Closed by abuaboud** 2024-10-13 20:27 UTC
