### ISSUE TITLE
[BUG]: the code piece fails

### ISSUE THREAD

**Issue by geosimarg** [activepieces/activepieces#2759] opened 2023-09-20 13:32 UTC
**Describe the bug**
The trigger options for Square and Slack are not appearing.

**To Reproduce**
1. I just set up the container and opened localhost:8080.

**Expected behavior**
I set up a container, and when trying to use Square as a trigger, the list appears empty, even though debugging the API communication shows the number 7, indicating that there are 7 items in triggers.

**Screenshots**
![image](https://github.com/activepieces/activepieces/assets/71460282/6ae38807-4511-4276-91b7-6a47a1d93c4c)

**Comment by abuaboud** [comment] 2023-09-25 08:09
Hi @geosimarg 

Square / Slack / Facebook Leads are currently not supported in self hosted environment (Technical reason not commercial) , we call them App webhooks.

They only support 1 Webhook per application and has initial manual setup, we can't make it available for self hosters without creating an external service on our side to parse these events and route them to  correct instance on self hosting (which this service has cost on our us and it will parse everyone events so it's not an option).

The other solution is to create tutorial how to setup these apps manually like blogs and slight modification on our side but we didn't have time to do it, and are welcoming contribution.

https://github.com/activepieces/activepieces/issues/765

**Comment by abuaboud** [comment] 2023-09-25 08:09
Closing this as duplicate of https://github.com/activepieces/activepieces/issues/765

**Closed by abuaboud** 2023-09-25 08:09 UTC
