### ISSUE TITLE
[BUG]: SQLite error on login in dev mode

### ISSUE THREAD

**Issue by DesertStrom16** [activepieces/activepieces#4425] opened 2024-04-11 20:35 UTC
**Describe the bug**
Upon attempting to login using "dev@ap.com" and "12345678" I receive this error:
`"SQLITE_ERROR: no such column: folder.members",`

**To Reproduce**
1. Open WSL terminal and clone fresh repo.
2. Run setup script
3. Build packages and run dev
4. Try to login with default dev credentials

**Expected behavior**
A successful login without errors.

**Screenshots**

**Additional context**
I am running Ubuntu with WSL as well as using the .devcontainer in VSCode. Not sure if that makes a difference, but when I did all this without WSL and .devcontainer the login worked just fine.

**Comment by abuaboud** [comment] 2024-04-11 22:50
Hi @DesertStorm16,

I can't reproduce the issue. I deleted the `dev` folder, which contains the SQLite database, and did a fresh install. I can log in normally.

I am also curious because I don't remember we have a field like `folder.members`.

Try delete dev folder and run `npx nx reset`, and try again on the main commit, do you still can reproduce?

Thank you,
Mo.

**Comment by abuaboud** [comment] 2024-04-16 10:36
Closing Issue @DesertStrom16 

Please let me know if this fixes your issue, reopen if it doesn't

**Closed by abuaboud** 2024-04-16 10:36 UTC
Labels: 🤷‍♂️ action required
