### ISSUE TITLE
Asana Due Date & Assigned User

### ISSUE THREAD

**Issue by Preet14705** [activepieces/activepieces#1308] opened 2023-05-22 13:59 UTC
**Describe your usecase.**
I want to assign tasks to my asana when new record is created in Airtable and I am having issues with assigning tasks to asana users using their tags & I also want to add due on, but I only have option for Task name & Task description

**Describe alternatives you've considered**
I haven't tried anything new

**Comment by abuaboud** [comment] 2023-05-23 00:38
Hi @Preet14705,

Thank you for submitting the enhancement request for Asana. Just to clarify, would you like to assign specific tags to these tasks that remain static (same tags for all issues), or would you like to retrieve these tags from Airtable?

**Comment by Preet14705** [comment] 2023-05-23 04:41
I would like to retrieve tags from Airtable

**Comment by abuaboud** [comment] 2023-05-23 13:24
@Preet14705 The update has been implemented and is now available for use. To add tags, simply click on the "X" button and refer to the corresponding value from Airtable.

![image](https://github.com/activepieces/activepieces/assets/1812998/3d8372d8-16da-4b51-a938-d86d83f796f2)

If everything has gone smoothly, please close the issue.

**Comment by Preet14705** [comment] 2023-05-23 14:12
![Screenshot 2023-05-23 194039](https://github.com/activepieces/activepieces/assets/134298010/e07fbb73-fe0a-404f-90d8-8fe49b09e1b2)

It's not working

**Comment by Preet14705** [comment] 2023-05-23 14:17
![kjbiaisvd](https://github.com/activepieces/activepieces/assets/134298010/7b882bae-813e-4775-9867-3898f7ee1fa3)

**Comment by abuaboud** [comment] 2023-05-23 14:53
@Preet14705 I understand the issue. The "tags" field is expecting an array, but as a temporary workaround, you can use the "Data Mapper" to solve the problem.

Here are the steps to follow:

1. First, use the "Data Mapper" component in your workflow.
2. Configure the "Data Mapper" component to transform your data into an array format.
3. Once you have transformed the data into an array, you can use it inside the "tags" field.

Here is an example image illustrating the setup:

![Data Mapper](https://github.com/activepieces/activepieces/assets/1812998/4c34e411-edec-4219-89e7-bcf759a7a521)

After applying this workaround, the issue with the "tags" field should be resolved. However, please note that this is a temporary solution. The root cause of the issue, which involves displaying correct errors and converting the value to an array without a new step, is being addressed in the following tickets:

1. [Issue #771](https://github.com/activepieces/activepieces/issues/771) - Fixing the root cause of the error display.
2. [Issue #1018](https://github.com/activepieces/activepieces/issues/1018) - Providing a way to convert the value to an array without an additional step.

I apologize for the inconvenience caused, and we are actively working on improving this situation.

**Comment by abuaboud** [comment] 2023-05-23 14:57
@Preet14705 Make sure you replace trigger.method with correct path from the dropdown menu.

**Comment by Preet14705** [comment] 2023-05-23 16:48
@abuaboud I followed every step but it's still not working

**Comment by abuaboud** [comment] 2023-05-26 22:25
Closing this issue as this one related to Asana should be fixed, please let me know if there is any other issue feel free to reopen.

**Closed by abuaboud** 2023-05-26 22:25 UTC
Labels: ⭐ enhancement, question, 🔌 pieces, 💥 action
