### ISSUE TITLE
[BUG]: google calander auth store fails

### ISSUE THREAD

**Issue by codeWarriors-pro** [activepieces/activepieces#3479] opened 2023-12-23 08:44 UTC
I'm facing the issue with google calendar when i connect with the google account try to store the auth it return the error INVALID_CLOUD_CLAIM

![image](https://github.com/activepieces/activepieces/assets/114612630/34ed07e6-0586-4c0b-9606-6661999c2f30)

**Comment by AbdulTheActivePiecer** [comment] 2023-12-24 11:49
Hello
Is this happening when you create your connection via our platform piece, API or our UI at https://cloud.activepieces.com ?

**Comment by AbdulTheActivePiecer** [comment] 2023-12-24 11:50
if it is via our UI please make sure you have no AdGuard turned on or anything (extensions or otherwise) that would block pop ups and if it is via our API are you sure of your payload ?

**Comment by codeWarriors-pro** [comment] 2023-12-25 06:37
this is happening when I create  connection via your API 
 https://secrets.activepieces.com/claim

**Comment by codeWarriors-pro** [comment] 2023-12-25 06:41
and payload look like below this
appName: "@activepieces/piece-google-calendar",
name: "google-calendar",
type: "CLOUD_OAUTH2",
value: {
  client_id: "674512252699-45rosiff4jgk4j4ud7q6a0m1na4411gi.apps.googleusercontent.com",
  code: "4/0AfJohXn4XF0jxUnXnQWBOZG4aoBh-5loTs7ErKsgI9UuW18wq_6nskeytDD1CKh_n3es1g",
  code_challenge: "JSsfLhLG7reB9qzbXb2JN",
  scope: "https://www.googleapis.com/auth/calendar.events https://www.googleapis.com/auth/calendar.readonly",
  token_url: "https://oauth2.googleapis.com/token",
  type: "CLOUD_OAUTH2"
  }

**Comment by codeWarriors-pro** [comment] 2023-12-29 11:41
@AbdulTheActivePiecer any feedback here ?

**Comment by codeWarriors-pro** [comment] 2024-01-04 21:25
@abuaboud any insights?

**Comment by abuaboud** [comment] 2024-01-05 01:13
Hello @codeWarriors-pro,

Could you test this issue on the cloud? It seems there is a network problem between your container and secrets.activepieces.com. One alternative is to create an OAuth2 app on Google and use it instead of the cloud-based one.

Cl lick on "Use your own credentials" 
[image](https://github.com/activepieces/activepieces/assets/1812998/8f4cceaf-33a8-4603-9c29-490e2ec170f6)

It's difficult to pinpoint the problem as I couldn't reproduce it. If you have any insights or know of any way to reproduce this, please let me know.

**Comment by abuaboud** [comment] 2024-01-06 13:27
Hi @codeWarriors-pro 

Please try again, we moved secrets to another host without cold boot, it might solve the issue, I am closing this issue please free to reopen.

**Closed by abuaboud** 2024-01-06 13:27 UTC
Labels: question
