### ISSUE TITLE
[BUG]: cannot install piece

### ISSUE THREAD

**Issue by LinusOssmann** [activepieces/activepieces#5112] opened 2024-07-14 18:10 UTC
**Describe the bug**
I published a piece on the registry and could also install it on an activepieces instance. After I synced my fork of activepieces I could not insttall the piece anymore

activepieces_1  | {"level":50,"time":1720980399578,"pid":280,"hostname":"b136ee1f2045","err":{"type":"Error","message":"ENOENT: no such file or directory, copyfile 'dist/packages/engine/main.js' -> '/usr/src/app/dist/packages/server/api/cache/main.js'","stack":"Error: ENOENT: no such file or directory, copyfile 'dist/packages/engine/main.js' -> '/usr/src/app/dist/packages/server/api/cache/main.js'","errno":-2,"code":"ENOENT","syscall":"copyfile","path":"dist/packages/engine/main.js","dest":"/usr/src/app/dist/packages/server/api/cache/main.js"},"msg":"[PieceService#add]"}

**To Reproduce**
1. Go to settings
2. Add a custom piece
3. Check application logs

**Expected behavior**
piece should be added correctly

**Screenshots**

**Additional context**

**Comment by abuaboud** [comment] 2024-07-14 21:31
Thank you for reporting the bug.

Can you please provide the link to the piece If it's in npm registry, It would make things easier to reproduce

**Comment by LinusOssmann** [comment] 2024-07-15 19:58
Yes of course. This is the package https://www.npmjs.com/package/@contentfleet/piece-amazon-paapi
I could install it on the default docker image (0.28.0), but on the latest master (did not try 0.29.1 - latest release) it does not work

**Comment by abuaboud** [comment] 2024-07-17 11:39
Hi @LinusOssmann 

@hazemadelkhalel will take it from there.

**Comment by hazemadelkhalel** [comment] 2024-07-17 11:43
I found that in "buying-price.js" you require the package "paapi5-typescript-sdk" but in your package.json file, it does not exist in the dependencies.

I think something went wrong with publishing using the nx command, do you have a public fork where we can reproduce the issue and fix the issue?

**Comment by LinusOssmann** [comment] 2024-07-24 08:37
Hey, unfortunately the fork is not public. I had the dependency installed in the package, but I had to install it in my forked activepieces package.json to make it work. I followed https://www.activepieces.com/docs/developers/piece-reference/external-libraries which said I had to install it in the main package.json. I do not think the error is caused by that tbh.

**Comment by abuaboud** [comment] 2024-07-28 14:28
Hi @LinusOssmann,

Just to confirm the issue, can you check the `dist/packages/pieces/custom/{pieceName}` folder after you build the piece? Do you see this in the generated `package.json`? If not, can you try to lint the piece, build it again, and check if it's there?

Run `npx nx lint {pieceFolderName} --fix`.

**Comment by abuaboud** [comment] 2024-09-01 12:43
Hi 

I am closing as we can't reproduce the issue. 

Please feel free to reopen.

Thank you,
Mo.

**Closed by abuaboud** 2024-09-01 12:43 UTC
Labels: 🤷‍♂️🤷‍♀️ untriaged
