### ISSUE TITLE
Facebook Leads Piece

### ISSUE THREAD

**Issue by ashrafsamhouri** [activepieces/activepieces#282] opened 2023-01-11 10:41 UTC
- Triggers:
    - New Lead.

**Comment by abuaboud** [comment] 2023-02-04 02:37
Stuck due to facebook business verification

**Comment by abuaboud** [comment] 2023-03-30 13:16
Closing this due duplicate of:

https://github.com/activepieces/activepieces/issues/933

**Closed** 2023-03-30 13:17 UTC
Labels: duplicate, 🔌 pieces
