### ISSUE TITLE
[Piece]: Add Highlevel

### ISSUE THREAD

**Issue by Activepieces-Apps** [activepieces/activepieces#1939] opened 2023-08-16 17:41 UTC
Highlevel is an all in one site-funnel-course-community builder. They primarily work with affiliates. They are the fastest growing platform online today. You will have an instant market of thousands of small businesses when you connect to them.

**Comment by ashrafsamhouri** [comment] 2023-08-20 15:46
Duplicate of https://github.com/activepieces/activepieces/issues/1905

**Closed by ashrafsamhouri** 2023-08-20 15:46 UTC
Labels: 🔌 pieces
