### ISSUE TITLE
[BUG]: Flow is exported with data: [object Object]

### ISSUE THREAD

**Issue by javix64** [activepieces/activepieces#4492] opened 2024-04-17 18:18 UTC
**Describe the bug**
I want to export a flow, but instead to get the JSON data with the flow, I get a file with the [object Object] data.

**To Reproduce**
1- Go to "My flows"
2- Select any flow that you want to export, click the tree points (options)
3- Click on: `Export`
4- You download a file called: `{flow}.json`, inside there is only the data: [object Object]

**Expected behavior**
You can download the flow without any problem.

**Screenshots**
![screenshot0](https://github.com/activepieces/activepieces/assets/58471170/38aa1d06-686e-48e8-a1f7-8c7273898a83)
![screenshot1](https://github.com/activepieces/activepieces/assets/58471170/ad07356a-abb5-4373-8337-ad3574256b6a)
![screenshot2](https://github.com/activepieces/activepieces/assets/58471170/8bf13dc8-7ec2-401e-8eb6-d258a68f0f60)

**Additional context**
As I had to deploy the container of Activepieces, I tried to run the project and replicate this issue, but:
1- I am not able to use any piece (probably I miss a step, I do not know)
2- I am able to download the flow, this is the data:

```json
{
  "created": "1713376499159",
  "updated": "1713376499159",
  "name": "Demo: The Gelato Factory 🍦",
  "description": "",
  "tags": [],
  "pieces": [],
  "template": {
    "displayName": "Demo: The Gelato Factory 🍦",
    "trigger": {
      "name": "trigger",
      "valid": false,
      "displayName": "Select Trigger",
      "type": "EMPTY",
      "settings": {
        "inputUiInfo": {}
      }
    },
    "valid": false
  },
  "blogUrl": ""
}
```

**Comment by abuaboud** [comment] 2024-04-17 18:44
It's will be released with next version

https://github.com/activepieces/activepieces/pull/4447

**Closed by abuaboud** 2024-04-17 18:44 UTC

**Comment by javix64** [comment] 2024-04-27 21:09
Hey @abuaboud. After upgrading Activepieces to the lastest version: `0.25.1`. 
The issue is the same.

Could you double check it?

Thanks!

**Comment by abuaboud** [comment] 2024-04-27 21:29
Hi @javix64 Are you sure it's 0.25.1? I can't reproduce it anymore on the cloud and this user also has it's fixed, they had similar issue when they Dm'd me

https://community.activepieces.com/t/importing-flow-ap-version-0-24-1/3933

**Comment by abuaboud** [comment] 2024-04-27 21:32
Hi @javix64 I tested on 0.25.1 locally and I can confirm it's working

**Comment by javix64** [comment] 2024-04-27 21:38
I will investigate deeply tomorrow. I do not know what I am doing wrong. 

Thanks anyway!

**Comment by javix64** [comment] 2024-04-28 09:55
Hey @abuaboud ! it is working fine. Probably the issue was something regarding cache.

Thanks!
Have a good day :smile:
