### ISSUE TITLE
[BUG]: fails to build docker image

### ISSUE THREAD

**Issue by magicman32** [activepieces/activepieces#3115] opened 2023-11-04 15:57 UTC
Following screenshot of whole process from git clone to docker build and fail

using ubuntu 22.04 LTS

![activepieces-git-clone-build](https://github.com/activepieces/activepieces/assets/15340872/0835da5c-4043-404e-bfe2-28cb250795ec)

**Comment by abuaboud** [comment] 2023-11-05 13:25
Hello @magicman32,

Could you attempt building the ap-base first and then using it here? If you encounter any problems, please inform me. I believe we should include this issue in the documentation.

Here are the commands to follow:
1. Build ap-base: `docker build -f ap-base.dockerfile .`
2. Update the image inside the `Dockerfile`.
3. Build the activepieces image: `docker build .`

**Comment by magicman32** [comment] 2023-11-06 14:23
Only tried step one and got an error

![activepieces-2](https://github.com/activepieces/activepieces/assets/15340872/a108ad1f-aa40-4240-876f-45d0fa4ccc58)

**Comment by dnburgess** [comment] 2023-11-06 14:53
Also tried this on Debian 12 running Docker and got this result:

![image](https://github.com/activepieces/activepieces/assets/5509008/e29951bf-6370-43d8-a406-7d8995b94fcb)

**Comment by ed0318** [comment] 2023-11-07 11:57
this command works on my end _sudo docker build -t activepieces ._

**Comment by dnburgess** [comment] 2023-11-07 12:38
> this command works on my end _sudo docker build -t activepieces ._

![image](https://github.com/activepieces/activepieces/assets/5509008/b273d45f-6ce7-468d-8ba7-c2d93788db97)

**Comment by magicman32** [comment] 2023-11-07 15:53
whats best distro to install on? does it make a difference?

**Comment by abuaboud** [comment] 2023-11-07 15:56
What is the docker version are you using? I do build on Linux Mint `Linux Mint 21.1 Vera \n \l`   and docker version `Docker version 24.0.2, build cb74dfc`

**Comment by abuaboud** [comment] 2023-11-07 15:58
I'll test on Ubuntu 22 (a fresh Droplet on DigitalOcean) and share the results shortly.

**Comment by abuaboud** [comment] 2023-11-07 16:12
Tested on Ubuntu 22 (LTS) and `Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1`.

It worked for me, which machines do you use so i can reproduce?

**Comment by dnburgess** [comment] 2023-11-07 16:20
I've tested it on Debian 12. Talking to @magicman32 on Discord, he mentioned that he's tried Ubuntu 22.04 LTS. It appears that we're getting the same (or similar) errors.

**Comment by abuaboud** [comment] 2023-11-07 16:22
Hello @dnburgess, can you include me in the conversation or mention me (@moabuaboud) on Discord?

**Comment by abuaboud** [comment] 2023-11-07 16:26
Dm'd you @dnburgess on discord, please check message requests

**Comment by dnburgess** [comment] 2023-11-07 16:28
I've got no messages. I tried adding @moabuaboud as a friend and it said that name didn't work
![image](https://github.com/activepieces/activepieces/assets/5509008/40fe6bf3-1869-4704-96cc-881bf83176d1)

**Comment by abuaboud** [comment] 2023-11-07 16:29
Sorry it's `abuaboud`, I already dm'd you

**Comment by dnburgess** [comment] 2023-11-07 17:29
After switching to an Ubuntu 22.04 VM (rather than a Proxmox container) I was able to get the image to build. Then I used the install command from the docs and everything whent as planned.

![image](https://github.com/activepieces/activepieces/assets/5509008/360db180-743f-4fc3-b65a-9d4373449c30)

**Comment by magicman32** [comment] 2023-11-09 14:36
I get to install also, but I cant save credentials

**Comment by abuaboud** [comment] 2023-11-11 00:22
Hi @magicman32 what is the issue in the logs? If it's encryption issue try clean database and re install.

That means AP_ENCRYPTION were generated then it were used then regenerated.

**Comment by abuaboud** [comment] 2023-11-17 02:00
It's related to changing storage overlay in docker.

https://github.com/nextcloud/all-in-one/discussions/1490#discussioncomment-7120799

I am closing this issue as the issue is no longer there.

**Closed by abuaboud** 2023-11-17 02:00 UTC
Labels: question, 🤷‍♂️🤷‍♀️ untriaged
